### ISSUE TITLE
Error @self.SourceImgTOP.save( colorImgFilePath , async=False )

### ISSUE THREAD

**Issue by Gamgie** [raganmd/touchdesigner-dominant-color#7]
Hello 

I'm trying to use this module which look amazing !
But for now, I can't get it done.

I could install everything in P3.5 version but couldn't import scipy due to an error in importing "typing".

![image](https://user-images.githubusercontent.com/4440017/78280602-a91b6b00-7519-11ea-9397-b99a60721b30.png)

**Is it mandatory Python 3.5 or not ?**

So I installed Python 3.6 (as advised online with this kind of trouble) and everything work great : installation and import in python environment.
I tried then to launch the tox file. I have an error and I don't really understand where that could come from.
![image](https://user-images.githubusercontent.com/4440017/78280444-65286600-7519-11ea-95b8-477d76f0dacc.png)

I don't have the python tab in the comp node to test my module installation.

![image](https://user-images.githubusercontent.com/4440017/78280498-7c675380-7519-11ea-959e-a12499cc17a1.png)

I tried to import module manually and adding them in the "python 64 bit module path" in pref but nothing solve the problem.

If you have any idea to make this work, it would be awesome 👍

**Comment by raganmd** [comment]
Oh bother.

Looks like there have been some changes on the TouchDesigner side of the equation here since this was last updated. The move to 3.7 will have some impact here for sure. 

The 3.5 requirement is largely in place so the helper functions correctly fetch the appropriate build for Touch - as it's pretty difficult to pip install / not ideal to install directly into the TD install directory. 

One piece is the keyword change of `async` to `asynchronous` which is the grumble you're seeing there. Doing some other quick work it looks like there might also be some cv2 conflicts and I'd suspect that sklearn is going to have some wobbles here as well. 

Doing some initial looking - there's definitely something amiss here. I'll try to find some time this weekend to do some deeper investigation.

**Comment by Gamgie** [comment]
Thanks for your answer. I'll tell you if I find something on my side. But for now I'm not very familiar with python and external module but I'll give it a try (I really want try this dominant color !! )

**Comment by Gamgie** [comment]
Okay so I installed python 3.7 

![image](https://user-images.githubusercontent.com/4440017/78353132-db74a900-75a9-11ea-818f-aef415a61d09.png)

Changing `async `to `asynchronous `did the job for me.
I also add my lib path to the external python search path. 

Be careful, even though your python directory is 
`C:\Program Files\Python37\`
pip may install your lib in a user dependent path (depending on the option you give him when installing). For me it was
`C:\Users\YourName\AppData\Roaming\Python\Python37\site-packages`

And it worked !
I don't have the python tab in the node though.

Thanks a lot !
